package com.gerenciasuporte;

import javax.swing.JFrame;

/**
 *
 * @author Natalia
 */
public class MainForm extends javax.swing.JFrame {

    //Suporte quarto = new Suporte();
    
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        menuBarra = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuObterSuporte = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuConsultarSuporte = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setText("Menu");
        menu.setFont(new java.awt.Font("Calibri", 0, 14));

        menuObterSuporte.setFont(new java.awt.Font("Calibri", 0, 14));
        menuObterSuporte.setText("Obter suporte");
        menuObterSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActionPerformed(evt);
            }
        });
        menu.add(menuObterSuporte);
        menu.add(jSeparator1);

        menuConsultarSuporte.setFont(new java.awt.Font("Calibri", 0, 14));
        menuConsultarSuporte.setText("Consultar suporte");
        menuConsultarSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu.add(menuConsultarSuporte);
        menu.add(jSeparator2);

        menuBarra.add(menu);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        pack();
    }

    private void jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        /* formClientes = new SuporteObter();
        formClientes.setVisible(true);
        formClientes.pack();
        formClientes.setLocationRelativeTo(null);
        formClientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);*/
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        SuporteConsultar formQuartos = new SuporteConsultar();
        formQuartos.setVisible(true);
        formQuartos.pack();
        formQuartos.setLocationRelativeTo(null);
        formQuartos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	MainForm mainForm = new MainForm();
            	mainForm.setVisible(true);
            	mainForm.setLocationRelativeTo(null);
            }
        });
    }

    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem menuObterSuporte;
    private javax.swing.JMenuItem menuConsultarSuporte;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
}
