package com.gerenciasuporte;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;

/**
 *
 * @author Natalia
 */
public class SuporteConsultar extends javax.swing.JFrame implements Objeto{

    My_Connection mycon = new My_Connection();
    
    public SuporteConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuartos = new javax.swing.JTable();
        jButtonRemoverQuarto = new javax.swing.JButton();
        jButtonLimparCamposQuarto = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Consultar Suporte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de suporte:");

        jTableQuartos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTableQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Cidade", "País", "Hora de início", "Hora de encerramento", "Tipo de suporte", "Telefone"
            }
        )
        //não deixa as células da tabela editável
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTableQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableQuartosMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTableQuartos);

    jButtonRemoverQuarto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
    jButtonRemoverQuarto.setText("Pesquisar");
    jButtonRemoverQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoverQuarto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoverQuartoActionPerformed(evt);
        }
    });

    jButtonLimparCamposQuarto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
    jButtonLimparCamposQuarto.setText("Gerar relatório");
    jButtonLimparCamposQuarto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonLimparCamposQuartoActionPerformed(evt);
        }
    });

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma opção>", "Hardware", "Rede", "Banco de dados/aplicação" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(294, 294, 294))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldIdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonLimparCamposQuarto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonRemoverQuarto)))
                    .addGap(79, 79, 79)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(16, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldIdQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRemoverQuarto)
                        .addComponent(jButtonLimparCamposQuarto))))
            .addContainerGap(58, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparCamposQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposQuartoActionPerformed
        //jTextFieldIdQuarto.setText("");
        String tipoSuporte = (String) jComboBox1.getSelectedItem();
        geraRelatorio(tipoSuporte);
    }//GEN-LAST:event_jButtonLimparCamposQuartoActionPerformed

    private void jButtonRemoverQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverQuartoActionPerformed
        String tipoSuporte = (String) jComboBox1.getSelectedItem();
        jTableQuartos.setModel(new DefaultTableModel(null, new Object[]{"id", "Cidade", "Pais", "HoraInicio", "HoraEncerra", "TipoSuporte", "Telefone"}));
        consultaObjeto(jTableQuartos,tipoSuporte);
    }//GEN-LAST:event_jButtonRemoverQuartoActionPerformed

    private void jTableQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQuartosMouseClicked

        DefaultTableModel model = (DefaultTableModel)jTableQuartos.getModel();

        int rIndex = jTableQuartos.getSelectedRow();
        jTextFieldIdQuarto.setText(model.getValueAt(rIndex, 0).toString());
    }//GEN-LAST:event_jTableQuartosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuporteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuporteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuporteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuporteConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuporteConsultar().setVisible(true);
                /*GerenciarClientes formClientes = new GerenciarClientes();
                formClientes.setVisible(true);
                formClientes.pack();
                formClientes.setLocationRelativeTo(null);
                formClientes.setExtendedState(JFrame.MAXIMIZED_BOTH);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimparCamposQuarto;
    private javax.swing.JButton jButtonRemoverQuarto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableQuartos;
    private javax.swing.JTextField jTextFieldIdQuarto;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean insereObjeto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean alteraObjeto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean deletaObjeto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void consultaObjeto(JTable tabelaSuporte, String tipoSuporte) {
        PreparedStatement ps;
        ResultSet rs;
        
        String selectQuery = "SELECT * FROM `dadossuporte` WHERE `TipoSuporte` LIKE ?";
        
        try {
            ps = mycon.criarConexao().prepareStatement(selectQuery);
            ps.setString(1, tipoSuporte);
            rs = ps.executeQuery();
            DefaultTableModel tabelaModel = (DefaultTableModel) tabelaSuporte.getModel();
            
            Object[] row;
            while(rs.next())
            {
                row = new Object[7];
                row[0] = rs.getInt(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                row[3] = rs.getString(4);
                row[4] = rs.getString(5);
                row[5] = rs.getString(6);
                row[6] = rs.getInt(7);
                
                tabelaModel.addRow(row);
            }
                    
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void geraRelatorio(String tipoSuporte){
        PreparedStatement ps;
        ResultSet rs;
        
        String selectQuery = "SELECT * FROM `dadossuporte` WHERE `TipoSuporte` LIKE ?";
        
        try {
            ps = mycon.criarConexao().prepareStatement(selectQuery);
            ps.setString(1, tipoSuporte);
            rs = ps.executeQuery();
            
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet abaManual = workbook.createSheet("Suportes disponiveis");
            
            HSSFFont fsTitle = workbook.createFont();
            fsTitle.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
            fsTitle.setColor(HSSFColor.WHITE.index);
            
            HSSFCellStyle sTitle = workbook.createCellStyle();
            sTitle.setFont(fsTitle);
            sTitle.setBorderBottom((short) 1);
            sTitle.setBorderLeft((short) 1);
            sTitle.setBorderRight((short) 1);
            sTitle.setBorderTop((short) 1);
            sTitle.setFillForegroundColor(HSSFColor.GREY_40_PERCENT.index);
            sTitle.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
            
            HSSFCellStyle sLinha1 = workbook.createCellStyle();
            sLinha1.setBorderBottom((short) 1);
            sLinha1.setBorderLeft((short) 1);
            sLinha1.setBorderRight((short) 1);
            sLinha1.setBorderTop((short) 1);
            sLinha1.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
            sLinha1.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);

            HSSFCellStyle sLinha2 = workbook.createCellStyle();
            sLinha2.setBorderBottom((short) 1);
            sLinha2.setBorderLeft((short) 1);
            sLinha2.setBorderRight((short) 1);
            sLinha2.setBorderTop((short) 1);

            FileOutputStream fos = null;
            
            try	{
                File file = File.createTempFile("relatorioSuporteDisponiveis", ".xls");
                fos = new FileOutputStream(file);

                HSSFRow row0 = abaManual.createRow(0);
                HSSFCell cell0 = row0.createCell(0);
                cell0.setCellValue("Relatório: ");
                cell0.setCellStyle(sTitle);

                HSSFCell cell1 = row0.createCell(1);
                GregorianCalendar dataAtual = new GregorianCalendar();
                SimpleDateFormat fmt = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");
                fmt.setCalendar(dataAtual);
                String dateFormatted = fmt.format(dataAtual.getTime());
                cell1.setCellValue(dateFormatted);
                cell1.setCellStyle(sTitle);

                HSSFRow row1 = abaManual.createRow(1);
                HSSFCell cell2 = row1.createCell(0);
                cell2.setCellValue("");

                HSSFRow row = abaManual.createRow(3);

                HSSFCell cell0Title = row.createCell(0);
                cell0Title.setCellValue("Cidade");
                cell0Title.setCellStyle(sTitle);

                HSSFCell cell1Title = row.createCell(1);
                cell1Title.setCellValue("País");
                cell1Title.setCellStyle(sTitle);

                HSSFCell cell2Title = row.createCell(2);
                cell2Title.setCellValue("Hora de início");
                cell2Title.setCellStyle(sTitle);

                HSSFCell cell3Title = row.createCell(3);
                cell3Title.setCellValue("Hora de encerramento");
                cell3Title.setCellStyle(sTitle);

                HSSFCell cell4Title = row.createCell(4);
                cell4Title.setCellValue("Tipo de suporte");
                cell4Title.setCellStyle(sTitle);

                HSSFCell cell5Title = row.createCell(5);
                cell5Title.setCellValue("Telefone");
                cell5Title.setCellStyle(sTitle);
                
                int i = 6;
                while(rs.next()){

                        Object req = rs.getString(2);
                        System.out.println(req);
                        Object cpf = rs.getString(3);			
                        System.out.println(cpf);
                        Object cpl = rs.getString(4);
                        System.out.println(cpl);
                        Object inscMunicipal = rs.getString(5);
                        System.out.println(inscMunicipal);
                        Object razaoSocial = rs.getString(6);
                        System.out.println(razaoSocial);
                        Object dataAutodeclaracao = rs.getInt(7);
                        System.out.println(dataAutodeclaracao);

                        row = abaManual.createRow(i);

                        popularLinhas(sLinha1, sLinha2, i, row, req, cpf, cpl, inscMunicipal, razaoSocial, dataAutodeclaracao);
                        i++;
                }

                File currDir = new File(".");
                String path = currDir.getAbsolutePath();
                System.out.println(path);
                String fileLocation = path.substring(0, path.length() - 1) + "relatorioSuporte.xls";
                System.out.println(fileLocation);
                FileOutputStream outputStream = new FileOutputStream(fileLocation);
                workbook.write(outputStream);
                outputStream.close();
        }
        catch (IOException e)
        {
        }
            
        Object[] row;
        while(rs.next())
        {
            row = new Object[7];
            row[0] = rs.getInt(1);
            row[1] = rs.getString(2);

            row[2] = rs.getString(3);
            /*String horaInicio = row[2].toString();
            String priPosicao[] = horaInicio.split(":");
            Integer inicio = 0;
            Integer fim = 0;

            for(String x : priPosicao)
            {
                x = x.substring(0,1);
            }*/

            row[3] = rs.getString(4);

            row[4] = rs.getString(5);
            row[5] = rs.getString(6);
            row[6] = rs.getInt(7);

            //tabelaModel.addRow(row);
        }
                    
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void popularLinhas(HSSFCellStyle sLinha1, HSSFCellStyle sLinha2, int i, HSSFRow row, Object req, Object cpf, Object cpl, Object inscMunicipla, Object razaoSocial, Object dataAutodeclaracao) {

        //Cidade
        HSSFCell cell0 = row.createCell(0);
        if (req != null){
                cell0.setCellValue(req.toString().toUpperCase());
        }else {
                cell0.setCellValue("");
        }

        //Pais
        HSSFCell cell1 = row.createCell(1);
        if (cpf != null){
                cell1.setCellValue(cpf.toString());
        }else {
                cell1.setCellValue("");
        }	

        //HoraInicio
        HSSFCell cell2 = row.createCell(2);
        if (cpl != null){
                cell2.setCellValue(cpl.toString());
        }
        else {
                cell2.setCellValue("");
        }
        //HoraEncerra
        HSSFCell cell3 = row.createCell(3);
        if (inscMunicipla != null){
                cell3.setCellValue(inscMunicipla.toString());
        }
        else {
                cell3.setCellValue("");
        }
        
        //TipoSuporte
        HSSFCell cell4 = row.createCell(4);
        if (razaoSocial != null){
                cell4.setCellValue(razaoSocial.toString());
        }
        else {
                cell4.setCellValue("");
        }

        //Telefone
        HSSFCell cell5 = row.createCell(5);
        if (dataAutodeclaracao != null){
                String dataFormatada = dataAutodeclaracao.toString();
                cell5.setCellValue(dataFormatada);
        }
        else {
                cell5.setCellValue("");
        }

        if (i % 2 == 0) {
                cell0.setCellStyle(sLinha1);
                cell1.setCellStyle(sLinha1);
                cell2.setCellStyle(sLinha1);
                cell3.setCellStyle(sLinha1);
                cell4.setCellStyle(sLinha1);
                cell5.setCellStyle(sLinha1);
        }
        else {
                cell0.setCellStyle(sLinha2);
                cell1.setCellStyle(sLinha2);
                cell2.setCellStyle(sLinha2);
                cell3.setCellStyle(sLinha2);
                cell4.setCellStyle(sLinha2);
                cell5.setCellStyle(sLinha2);
        }
    }
}
